import fs from "node:fs";
import path from "node:path";
const root=process.cwd();
const checkOnly=process.argv.includes("--check");
const sourcePath=path.join(root,"content","news.json"),homePath=path.join(root,"index.html"),archivePath=path.join(root,"news","index.html"),newsRoot=path.join(root,"news");
const startMarker="<!-- NEWS:GENERATED:START -->",endMarker="<!-- NEWS:GENERATED:END -->";
const read=file=>fs.readFileSync(file,"utf8"),write=(file,value)=>fs.writeFileSync(file,value,"utf8");
const esc=value=>String(value).replace(/[&<>"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[char]));
const dateLabel=value=>{const p=value.split("-");return p[0]+"."+p[1]+"."+p[2];};
const stableSort=items=>[...items].sort((a,b)=>b.date.localeCompare(a.date)||a.slug.localeCompare(b.slug));
function fail(message){throw new Error(message);}
function validateSource(items){if(!Array.isArray(items)||items.length===0)fail("content/news.json must contain at least one news record");const slugs=new Set(),urls=new Set();for(const item of items){for(const field of ["slug","date","source","category","title","summary","sourceUrl"])if(typeof item[field]!=="string"||item[field].trim()==="")fail("news field missing: "+field);if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(item.slug))fail("invalid news slug: "+item.slug);if(!/^\d{4}-\d{2}-\d{2}$/.test(item.date))fail("invalid news date: "+item.date);if(!/^https?:\/\//.test(item.sourceUrl))fail("news source URL must be http(s): "+item.sourceUrl);if(slugs.has(item.slug))fail("duplicate news slug: "+item.slug);if(urls.has(item.sourceUrl))fail("duplicate news source URL: "+item.sourceUrl);if(item.author!=null&&typeof item.author!=="string")fail("news author must be string: "+item.slug);if(item.editor!=null&&typeof item.editor!=="string")fail("news editor must be string: "+item.slug);slugs.add(item.slug);urls.add(item.sourceUrl);}if(JSON.stringify(items)!==JSON.stringify(stableSort(items)))fail("content/news.json must already be in reverse chronological order");}
function replaceGeneratedBlock(source,body,file){const start=source.indexOf(startMarker),end=source.indexOf(endMarker);if(start<0||end<start)fail("generated block markers missing: "+file);return source.slice(0,start)+startMarker+"\n"+body+"\n"+endMarker+source.slice(end+endMarker.length);}
function homepageBody(items){return items.map(item=>['<article class="media-card">','<div class="media-meta"><strong class="media-date">'+esc(dateLabel(item.date))+'</strong><span>'+esc(item.source)+'</span><span>'+esc(item.category)+'</span></div>','<div class="media-body">','<h3 class="media-title">'+esc(item.title)+'</h3>','<p class="media-summary">'+esc(item.summary)+'</p>','<a class="media-action" href="'+esc(item.sourceUrl)+'" target="_blank" rel="noopener noreferrer"><span>查看原文</span><span aria-hidden="true">↗</span></a>','</div>','</article>'].join("\n")).join("\n");}
function archiveBody(items){return items.map(item=>['<article class="news-list-card">','<div class="news-list-meta"><strong>'+esc(dateLabel(item.date))+'</strong><span>'+esc(item.source)+'</span><span>'+esc(item.category)+'</span></div>','<div class="news-list-body">','<h2>'+esc(item.title)+'</h2>','<p>'+esc(item.summary)+'</p>','<a class="media-action" href="/news/'+esc(item.slug)+'/"><span>查看报道</span><span aria-hidden="true">→</span></a>','</div>','</article>'].join("\n")).join("\n");}
function detailPage(item){const people=(item.author||item.editor)?'<div class="news-article-summary"><strong>作者：</strong>'+esc(item.author||"—")+'　<strong>编辑：</strong>'+esc(item.editor||"—")+'</div>':"";return ['<!doctype html>','<html lang="zh-CN">','<head>','<meta charset="utf-8">','<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">','<title>媒体报道｜'+esc(item.title)+'｜梦宠数智</title>','<meta name="description" content="'+esc("媒体报道："+dateLabel(item.date)+" "+item.source+"："+item.title)+'">','<meta name="theme-color" content="#f36b12">','<link rel="stylesheet" href="/css/tokens.css?v=20261008-r165">','<link rel="stylesheet" href="/css/base.css?v=20261006-r100">','<link rel="stylesheet" href="/css/media.css?v=20261006-r150">','</head>','<body class="news-page">','<a class="skip-link" href="#news-article">跳过导航，直接进入主要内容</a>','<header class="news-header"><div class="news-header-in">','<a class="brand" href="/" aria-label="返回梦宠数智首页"><img class="brand-wordmark" src="/assets/brand/brand.svg?v=20261006-r100" alt="梦宠数智" width="176" height="40"></a>','<a class="news-back" href="/news/"><span aria-hidden="true">←</span><span>媒体报道</span></a>','</div></header>','<main id="news-article" class="news-main" tabindex="-1"><article class="news-article">','<div class="eyebrow">MEDIA COVERAGE</div>','<h1>'+esc(item.title)+'</h1>','<div class="news-article-meta"><span>'+esc(dateLabel(item.date))+'</span><span>·</span><span>'+esc(item.source)+'</span><span>·</span><span>'+esc(item.category)+'</span></div>','<div class="news-article-summary">'+esc(item.summary)+'</div>',people,'<div class="news-source"><span>来源：'+esc(item.source)+'</span><a href="'+esc(item.sourceUrl)+'" target="_blank" rel="noopener noreferrer">查看原文 ↗</a></div>','</article></main>','<footer class="news-footer"><span>© 2026 辽宁梦宠数智科技有限公司 · montpets.com</span></footer>','</body>','</html>',''].join("\n");}
const items=stableSort(JSON.parse(read(sourcePath)));validateSource(items);const currentHome=read(homePath),currentArchive=read(archivePath);const expectedHome=replaceGeneratedBlock(currentHome,homepageBody(items),"index.html"),expectedArchive=replaceGeneratedBlock(currentArchive,archiveBody(items),"news/index.html");
const expectedPages=new Map(items.map(item=>[path.join(newsRoot,item.slug,"index.html"),detailPage(item)]));
const actualDirs=fs.readdirSync(newsRoot,{withFileTypes:true}).filter(entry=>entry.isDirectory()).map(entry=>entry.name).sort(),expectedDirs=items.map(item=>item.slug).sort();if(JSON.stringify(actualDirs)!==JSON.stringify(expectedDirs))fail("news detail directories do not match content/news.json");
if(checkOnly){if(currentHome!==expectedHome)fail("generated homepage media block is out of sync");if(currentArchive!==expectedArchive)fail("generated news archive is out of sync");for(const [file,expected] of expectedPages){if(!fs.existsSync(file))fail("generated news detail missing: "+path.relative(root,file));if(read(file)!==expected)fail("generated news detail is out of sync: "+path.relative(root,file));}console.log("NEWS GENERATION CHECK PASSED: "+items.length+" records");process.exit(0);}
write(homePath,expectedHome);write(archivePath,expectedArchive);for(const [file,expected] of expectedPages){fs.mkdirSync(path.dirname(file),{recursive:true});write(file,expected);}console.log("NEWS GENERATED: "+items.length+" records");